Tzahi12345/YoutubeDL-Material

backend/app.js, src/app/main/main.component.css, src/app/main/main.component.html, src/app/main/main.component.ts, src/app/posts.services.ts
Advanced mode now includes 2 new inputs for your YouTube username and password. These are currently *not* functioning in our testing because of a bug in youtube-dl, although I will be following their progress on this issue.
=> Add the ability to use youtube authentication

.gitignore, backend/app.js, backend/config.js, src/app/app.component.css, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/posts.services.ts, src/app/settings/settings.component.html, src/app/settings/settings.component.scss, src/app/settings/settings.component.spec.ts, src/app/settings/settings.component.ts
This PR adds a settings page in the top right corner of the app
=> Add settings page

backend/app.js, backend/config/default.json, backend/config/encrypted.json, backend/consts.js, backend/package.json, backend/subscriptions.js, src/app/app.module.ts, src/app/file-card/file-card.component.html, src/app/file-card/file-card.component.ts, src/app/main/main.component.html, src/app/main/main.component.ts, src/app/posts.services.ts, src/app/settings/settings.component.html, src/app/subscription/subscription-file-card/subscription-file-card.component.html, src/assets/default.json
Users can now enable youtube-dl archive functionality in the `Downloader` section of the settings.
Implements blacklisting functionality as well in a separate text file.
=> Implements youtube-dl archive functionality for downloader

backend/app.js, package.json, src/app/app.module.ts, src/app/dialogs/video-info-dialog/video-info-dialog.component.html, src/app/dialogs/video-info-dialog/video-info-dialog.component.scss, src/app/dialogs/video-info-dialog/video-info-dialog.component.spec.ts, src/app/dialogs/video-info-dialog/video-info-dialog.component.ts, src/app/file-card/file-card.component.css, src/app/file-card/file-card.component.html, src/app/file-card/file-card.component.ts, src/app/main/main.component.html, src/app/posts.services.ts, src/app/subscription/subscription-file-card/subscription-file-card.component.html, src/app/subscription/subscription-file-card/subscription-file-card.component.ts, src/app/subscription/subscription/subscription.component.html, src/app/subscription/subscription/subscription.component.scss, src/app/subscription/subscription/subscription.component.ts, src/app/subscriptions/subscriptions.component.ts
This PR brings in many updates to the subscriptions system to expand and streamline subscriptions.
* Already pushed to master, but the ability to search for videos within each subscription has been added
* Videos can now be sorted by various properties like upload date, name, file size, and video duration
* Added video info dialogs in both subscriptions and the normal file manager
* Videos for subscriptions can now be download all at once as a zip
=> Subscriptions v2

backend/app.js, backend/package.json
This PR modifies the backend so that updates to youtube-dl are checked on startup. This will increase the longevity and decrease the maintenance required for the project.
=> Auto update youtube-dl binaries on startup

backend/app.js, backend/config.js, backend/package.json, backend/subscriptions.js
Implements a better logging system using the [winston](https://www.npmjs.com/package/winston) library. Currently, it is not configurable but this should be easy to implement.
Logs are stored in `appdata/logs`. There is a separate file just for errors.
=> Better logging system using winston

src/app/app.component.css, src/app/app.module.ts, src/app/settings/settings.component.html, src/app/settings/settings.component.scss
Updates the settings menu to improve organization and performance of the dialog.
The expansion panels were switched with lazy-loaded tabs. See image below for a preview.
Note that the underlying default.json file is untouched, so this is not a breaking change :)
Closes #46.
EDIT:
Forgot to mention, this also fixes a UI bug with the dark mode toggle
=> Better settings menu

backend/app.js, src/app/app.module.ts, src/app/dialogs/share-media-dialog/share-media-dialog.component.html, src/app/dialogs/share-media-dialog/share-media-dialog.component.spec.ts, src/app/dialogs/share-media-dialog/share-media-dialog.component.ts, src/app/file-card/file-card.component.html, src/app/file-card/file-card.component.ts, src/app/main/main.component.html, src/app/main/main.component.ts, src/app/player/player.component.css, src/app/player/player.component.html, src/app/player/player.component.ts, src/app/posts.services.ts
Adds the ability to share audio files, video files, and playlists (non-subscriptions)
A simple URL is provided which can be shared with other users. Those users do not have the option to change the sharing preferences (can only be done by clicking on the video from the main page).
Included in this is a refactor of the way downloaded video/audio files are stored.
* Previously, downloaded audio/video files were retrieved by scanning the directory recursively each time. This meant that requests for files took around 130ms.
* In this new system, they are already stored in the database and so retrieval takes ~60ms now, an over 50% reduction in latency!
=> Video sharing

backend/app.js, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/components/downloads/downloads.component.html, src/app/components/downloads/downloads.component.spec.ts, src/app/components/downloads/downloads.component.ts, src/app/download-item/download-item.component.html, src/app/download-item/download-item.component.scss, src/app/download-item/download-item.component.ts, src/app/main/main.component.html, src/app/main/main.component.ts, src/app/player/player.component.html, src/app/player/player.component.ts, src/app/posts.services.ts
The downloading management system has been overhauled! It's now (mostly) server-side, meaning downloads between sessions can be seen in the new *Downloads manager*! See image below for a sneak peek of what this will look like:
The UI is still a work in progress, if you have any specific requests for the downloads manager, leave a comment on this PR.
**Added features:**
* New downloads manager (see above) to see all current and previous downloads on all sessions
* I may organize this by device rather than session in the future, but it requires using an outside library like [fingerprintjs2](https://github.com/Valve/fingerprintjs2)
* You can clear previous downloads to prevent clutter, and if an error occurs, the specific error will be shown
* Download progress is now shown for video …
=> Downloads system refactor

backend/.dockerignore, backend/Dockerfile
I just changed some little nit picks to improve caching, remove 2MB from the final image and removed the hardcoded apk server.
=> Docker improvements

src/app/settings/settings.component.html
Fixes #100 . I could not figure out how to properly translate it. We should have some docs on translating.
=> #100 Typo fix for logger

package-lock.json, package.json
Fixes #127 . However I'm not sure why `bindings` and `file-uri-to-path` got added automatically. Let me know if you'd like me to remove those edits.
=> Fixes #127 by adding nan to dependencies

backend/app.js, backend/db.js, backend/utils.js
This PR fixes #194 -- on startup, all subscription and non-subscription folders are checked (for all users if multi-user mode), and files missing from the DB will be added to its appropriate db location.
This also lays the groundwork for #157, which will allow for imports through the UI (coming in v4.3!)
=> Import files on startup

backend/app.js, backend/appdata/default.json, backend/authentication/auth.js, backend/config.js, backend/consts.js, backend/package-lock.json, backend/package.json, src/app/posts.services.ts, src/app/settings/settings.component.html
Added ability to register/login through LDAP
* Added ability to edit LDAP settings and whether to use LDAP or not in the users tab in the settings.
* If LDAP is selected, the login will use LDAP for authentication. A caveat here is that an existing account made without LDAP will still be accessible.
* This means that you cannot use LDAP accounts with the same username as existing (non-LDAP) accounts
* This also means that you can't override the default admin account, that will always be accessible using the normal method (and it's how you can elevate permissions for LDAP users)
**Preview:**
Closes #90, OAuth will not be implemented for the foreseeable future unless specific sites are used as information gathered from OAuth providers is dynamic (and thus unpredictable).
This has been …
=> Added ability to register/login through LDAP

backend/app.js, backend/appdata/default.json, backend/config.js, backend/consts.js, backend/db.js, backend/package.json, backend/subscriptions.js, backend/utils.js, src/app/components/unified-file-card/unified-file-card.component.html, src/app/components/unified-file-card/unified-file-card.component.ts, src/app/main/main.component.html, src/app/main/main.component.ts, src/app/settings/settings.component.html
Hi all!
This PR is designed to give users greater flexibility in their downloads and the data associated with it. It also fixes a nasty bug where the max quality was limited to the max mp4 quality available (if another video format existed with a higher quality, it was ignored).
While I intended to switch out the youtube-dl library used (see #111), I came up short of that goal as better alternatives didn't really exist. The one library that was promising didn't have all the features needed, so I decided to instead improve upon the existing functionality.
Previously, there was a "safe" and "normal" downloading method. The safe method was exactly that: safe. All args worked as expected, any errors seen were problems with youtube-dl and not with the driver or this app. But, it lacked one …
=> Downloader improvements - updated system and bug fixes

backend/app.js, backend/authentication/auth.js, src/app/player/player.component.ts, src/app/posts.services.ts
Small bug fix that allows playlists to be downloaded as a zip in multi-user mode
=> Fixed bug that preventing playlists from being downloaded a zip

backend/app.js, backend/authentication/auth.js, backend/db.js, backend/subscriptions.js, backend/utils.js
This should improve performance since it allows more operations to run in parallel!
- Replace `fs.existsSync` with `await fs.pathExists`
- Replace various sync methods with async methods
- Replace `new Promise` with `async` and `await` for readability.
=> Use async versions of filesystem methods

src/app/components/custom-playlists/custom-playlists.component.html, src/app/components/recent-videos/recent-videos.component.html, src/app/components/unified-file-card/unified-file-card.component.html, src/app/components/unified-file-card/unified-file-card.component.ts, src/app/posts.services.ts, src/app/settings/locales_list.ts, src/app/settings/settings.component.ts
Previously the dates used the date format only used in the US. Now it's localized. British English is now offered to allow for English with European/South American date formats.
=> File cards now use the locale to format dates

.github/workflows/docker.yml
Hi,
this PR would enable automated GitHub Actions-based docker builds for multiple architectures via [docker buildx](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images).
The resulting docker images are multi-platform themselves, i.e., you don't need separate tags for different CPU architectures. Using `latest` just works out of the box for all supported CPU architectures.
Thankfully, your `Dockerfile` actually already works for these builds, as `alpine` is now also a multi-arch image, and the separate tag for `arm` isn't required anymore.
With the current configuration, this would create images that support `linux/amd64`, `linux/arm`, and `linux/arm64/v8`, but you could add additional platforms.
The build would be moved from Dockerhub's own builds to GitHub …
=> Multi-arch docker image build via GitHub Actions

README.md
Hi,
this aligns the `README.md` to the GitHub-flavor markdown code-style and clarifies which port to use when deploying via Docker.
Let me know your thoughts:)
=> Cleanup & clarify README.md

backend/app.js, backend/appdata/default.json, backend/config.js, backend/consts.js, backend/twitch.js, src/app/app.module.ts, src/app/components/twitch-chat/twitch-chat.component.html, src/app/components/twitch-chat/twitch-chat.component.scss, src/app/components/twitch-chat/twitch-chat.component.spec.ts, src/app/components/twitch-chat/twitch-chat.component.ts, src/app/player/player.component.html, src/app/player/player.component.ts, src/app/posts.services.ts, src/app/settings/settings.component.html
Fixes #156 
This PR adds a chat sidebar for Twitch VODs, just click the new chat icon in the video player and you should be able to download VODs. Only caveat is you need to get a Twitch API key (located in the Extra tab), but this is fairly easy to generate (link to the instructions can be found in the settings).
This is a first iteration of the feature, I'd like to get feedback and improve on it before the next update drops. Let me know how it goes!
=> Added chat sidebar for Twitch VODs

backend/app.js, backend/appdata/default.json, backend/categories.js, backend/config.js, backend/consts.js, src/app/settings/settings.component.html, src/assets/default.json
Fixes an issue in categories where playlist downloads were not properly handled
=> Categories playlist download fix

chart/.helmignore, chart/Chart.yaml, chart/templates/NOTES.txt, chart/templates/_helpers.tpl, chart/templates/appdata-pvc.yaml, chart/templates/audio-pvc.yaml, chart/templates/deployment.yaml, chart/templates/ingress.yaml, chart/templates/service.yaml, chart/templates/serviceaccount.yaml, chart/templates/subscriptions-pvc.yaml, chart/templates/tests/test-connection.yaml, chart/templates/users-pvc.yaml, chart/templates/video-pvc.yaml, chart/values.yaml
Added a helm chart to be deployed on a k8s cluster
=> Helm chart

src/app/settings/settings.component.html
Updated the API documentation link in the settings
=> Update API docs links in settings

Dockerfile, backend/app.js, src/assets/i18n/messages.en.xlf
Small PR that fixes an issue where python3 not being installed on Docker causes yt-dlp to fail to download any videos.
=> yt-dlp python3 bugfix

backend/authentication/auth.js
=> Fixed issue preventing LDAP to create new account

Dockerfile, README.md, docker-compose.yml
Mention host-specific instructions :)
=> Readme update

src/app/components/recent-videos/recent-videos.component.html
<details>
<summary>Before changes</summary>
</details>
<details>
<summary>After changes</summary>
</details>
=> Fixed file type dropdown margin

src/api-types/models/DownloadFileRequest.ts, src/app/player/player.component.html, src/app/player/player.component.ts, src/app/posts.services.ts
Fix #486 #523
Added extra parameters to downloadFile function to prevent backend crashing.
Also, adds a new " download video" button because the current "floppy disk" button is unclear of it's purpose.
Needs re-compilation of front end.
=> Add download video button on player component.

README.md
Added Shorcut description on README.md : #477
=> Added Shortcut description

src/app/settings/settings.component.html, src/assets/i18n/messages.en.xlf
=> Made Global custom args hint clearer. (scope: EN)

Dockerfile
fixes #546 
Mazbe even decreases urgency of #544
=> Switch to alpine edge community repo for ffmpeg

Dockerfile
Update: fix missing \ in DOCKEFILE
=> Switch to alpine edge community repo for ffmpeg (fixed syntax)

Dockerfile
Waiting for alpine repo providing a good version. (5.x will have the change we need, not sure when that's out, 5.0.1-RC1 is not our savior here I'm afraid)
=> revert ffmpeg changees

backend/subscriptions.js
=> Fix for #480 - existing DLs still getting queued

docker-build.sh
=> fix pipefail MIA in ubuntu without specifying bash

Dockerfile
Added some commands to clean up the image after apt-get does its thing.
It should shave off a couple of megabytes, nothing to big though.
=> Clean up docker image

Dockerfile
=> Permissions fixes

Dockerfile
Hopefully hotfixes #608 by reverting Ubuntu version: https://github.com/NixOS/nixpkgs/issues/170279
=> Reverted ubuntu version to 20.04

.github/workflows/close-issue-if-noresponse.yml
=> Autoclose stale issues lacking requested response

.github/dependabot.yaml
With this file set up, you'll automatically get pull requests from [Dependabot](https://github.com/dependabot) for most of your dependencies - Dockerfile base images, Github Actions in your workflows and npm packages from the package.json files both for the backend and frontend.
=> Add Dependabot configuration

Dockerfile, ffmpeg-fetch.sh
Hi, 
This is two small improvements to this project to make it build more easy.
=> Mholmqvist patch 1

src/app/components/login/login.component.html
Nothing major. Still draft as there may be a thing or two to update as well.
* Login tabs now fill the entire component
* Expanded widths of inputs on login page to 100%
=> Login page UI improvements

package.json
Test PR to fix GH actions. Should *not* be merged yet.
=> GH actions fix

.vscode/launch.json, DEVELOPMENT.md, README.md
Not the most exciting or groundbreaking changes, but I thought I document some of the workflow I figured out. Since I am new to the whole node.js and web dev stuff, please correct me if I got anything wrong @Tzahi12345  :)
Changes:
* Added a new read me (DEVELOPMENT.md) as starting point for new develop
* Added a new VSC launch configuration to start the backend in the debugger 
* Update the build instruction in README.md (Issue #728)
=> Development Documentation

backend/package-lock.json, backend/package.json, backend/twitch.js
Minor bug fix
Fixed issue where twitch chat downloader could not be found in docker
=> Twitch chat downloader fix for Docker

.github/workflows/docker-pr.yml, Dockerfile, backend/entrypoint.sh, docker-utils/fetch-twitchdownloader.sh
* Make js generation respect buildplatform, instead cross generate that result long build time.
* Install pycryptodomex after apt install and remove build-essential
* PR CI also build triplet platform
* Change twitchdownload using bash scripts like ffmpeg due architectural issue
* Correcting platform `linux/amd64,linux/arm64,linux/arm/v7`
* Revert https://github.com/Tzahi12345/YoutubeDL-Material/commit/142d708ee3ca90601254785332f9cf4b98c2e896
=> docker : reduce build time and size

.github/workflows/docker.yml, backend/entrypoint.sh
* Revert https://github.com/Tzahi12345/YoutubeDL-Material/pull/864
Undetected due to maybe we don't play uid/gid so much, don't recurse, just find and change ownership
* Restore armv7 on nightly
* Regardless UID/GID do chown
=> Fix entrypoint.sh

backend/app.js, chart/Chart.yaml, package.json, src/app/consts.ts
Small PR for v4.3.2 release
* Fixes issue where users with nullish username/ids could get registered (closes #912)
=> 4.3.2 release

backend/downloader.js, backend/subscriptions.js, backend/utils.js, src/app/components/downloads/downloads.component.ts
* Fixes issue where playlists with missing videos wouldn't be able to get downloaded (closes #928)
* Fixed UI bug for paused videos that made the resume button appear twice
* Code cleanup
=> Downloader fixes

backend/app.js, backend/youtube-dl.js, src/app/main/main.component.ts, src/app/posts.services.ts
Quick bug fix PR:
* Fixed issue where video info could not be retrieved
* If youtube-dl update fails, error will show and server won't crash
=> Video info bug fix
