Tzahi12345/YoutubeDL-Material

.gitignore, Dockerfile, README.md, backend/app.js, backend/config.js, backend/config/default.json, backend/config/encrypted.json, backend/consts.js, backend/package.json, docker-compose.yml, src/app/app.component.ts, src/app/main/main.component.ts, src/app/player/player.component.ts, src/app/posts.services.ts, src/assets/default.json
This PR refactors the code such that the frontend app is not served by a user's webserver, but rather the nodejs YTDL-Material backend. This is to simplify the stack's deployment and routing configurations (one URL to deal with instead of two).
Backend routes are now prepended with /api/
=> Serve frontend app through nodejs

backend/app.js
This fixes an issue with video playback when using a different video path setting than the default "video/" .  Using the videoFolderPath variable rather than "video/" string.
=> Fix for custom video folder path

backend/app.js, backend/subscriptions.js, src/app/dialogs/subscribe-dialog/subscribe-dialog.component.html, src/app/dialogs/subscribe-dialog/subscribe-dialog.component.ts, src/app/dialogs/video-info-dialog/video-info-dialog.component.html, src/app/posts.services.ts, src/app/subscription/subscription-file-card/subscription-file-card.component.ts, src/app/subscription/subscription/subscription.component.ts
Added the ability to enable "streaming-only mode" for subscriptions. This can be set from the "Subscribe" dialog.
Subscriptions that have this option enabled will not download the videos, and instead will periodically get info on the videos like the stream URL, name, uploader, etc.
This mode doesn't come with many caveats. It significantly reduces disk usage from megabytes or gigabytes to just a few bytes for each video. Videos might take a few more seconds to load as they are streamed from an outside URL rather than directly from the file.
=> Streaming-only mode

backend/Dockerfile, backend/entrypoint.sh
This changes the docker image to allow it to run as non root. It also copies the lock file for npm in which I was to lazy to separate after fixing permissions issues. Startup time with default UID/GID is negligible effected but when changing them it takes a few seconds to chown all files.
=> Run docker as non root

backend/Dockerfile, backend/entrypoint.sh
This fixes https://github.com/Tzahi12345/YoutubeDL-Material/pull/116#issuecomment-637906815 and a mistake I did in the user switching which resulted in the user not being switched and node_modules being owned by root which increases the startup time.
=> Docker: Fix startup error in entrypoint, ownership of node_modules

backend/Dockerfile
The previous Dockerfile failed to build on Windows, and on the automated Docker build setup. This PR fixes that issue.
=> Updated Dockerfile to support Windows builds

README.md
I see package.json has output directory specified to `backend/public`. I updated the readme to reflect this. (Also trailing spaces are a problem in this repo, I'll upload a whitespace trim PR.
=> Updating README regarding output dir

backend/public/assets/i18n/messages.de.json, src/app/components/downloads/downloads.component.html, src/app/components/manage-user/manage-user.component.html, src/app/components/modify-users/modify-users.component.html, src/app/dialogs/about-dialog/about-dialog.component.html, src/app/download-item/download-item.component.html, src/app/settings/settings.component.html, src/assets/i18n/messages.de.json, src/assets/i18n/messages.de.xlf
See title.
As you can see below, the close button is not translated. (The shown item is only one of the many improvements).
And I've also uniformed the close button.
=> Make more items translatable

backend/Dockerfile-armhf, backend/authentication/auth.js, backend/package.json
Because bcrypt refused to install/compile on the docker image on my raspberry pi, I have found this workaround.
I'm not a programmer and I don't know the implications but it should interest some people...
=> Switch from bcrypt to bcryptjs to keep compatibility with Raspberry Pi and a Dockerfile-armhf bonus

armhf.Dockerfile, hooks/post_checkout, hooks/pre_build
The frontend build process broke ARM autobuilds -- QEMU could not be properly downloaded which caused the frontend build to fail. This PR fixes that by downloading QEMU in the Dockerfile rather than using Docker hooks.
=> Fix ARM autobuild

.github/workflows/docker.yml
Missed something in #257:
We don't want to build and especially push new Docker images for pull requests but only for new commits merged/pushed to master
=> do not push new docker images for pull requests

.github/workflows/build.yml
Hi,
as discussed in #257 this is a first draft for automatically building the app and creating (draft) releases for tagged commits.
Please forgive my ignorance here - web stuff was never my specialty :D So please have a look if the result looks as you would expect it and if e.g. the "prepare artifact upload" step makes sense like that. E.g. do the sub-folders change a lot? (-> we should not copy the sub-folders one by one but rather exclude others etc.)
It follows the basic steps as described in the `README.md` and then packages everything together so the result looks similar to previous releases here.
The build is triggered for any push to `master` or branches starting with `feat/`, tagged commits and pull requests.
The resulting archive is uploaded as a build artifact so it can be used …
=> Automated build & release via GitHub Actions

.github/workflows/build.yml
The GitHub actions job to automatically create a (draft) release for tagged commits introduced in #259 contained a small error regarding the release asset name.
It used the `github.ref` context variable to get the tag name to create a release asset name like `youtubedl-material-v4.3.zip`.
However, `github.ref` always includes the `refs/tags/` prefix. As forward slashes don't work in filenames, this breaks the build ([see here for example](https://github.com/Tzahi12345/YoutubeDL-Material/runs/1604409003?check_suite_focus=true)).
The fix for this is to extract the actual tag name from the `github.ref` context variable first by removing the `refs/tags/` prefix.
This is the same approach as e.g. the official GitHub create-release action …
=> Fix asset name in automated release creation

src/assets/default.json
See https://github.com/Tzahi12345/YoutubeDL-Material/issues/385 for context; setting this to a daily value instead of every five minutes means that updates still come in but it doesn't completely trample all other network traffic, especially if you have a lot of subscriptions.
=> Update default.json to use a longer update period

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.ts, src/app/components/login/login.component.html, src/app/components/login/login.component.scss, src/app/components/logs-viewer/logs-viewer.component.html, src/app/components/modify-users/modify-users.component.html, src/app/components/modify-users/modify-users.component.scss, src/app/components/recent-videos/recent-videos.component.html, src/app/main/main.component.css, src/app/main/main.component.html, src/app/main/main.component.ts, src/app/posts.services.ts, src/app/settings/settings.component.html, src/app/settings/settings.component.scss, src/app/settings/settings.component.ts, src/styles.scss
Settings have been a dialog for a while, but with so many tabs added it's become a bit too tight, especially for those on mobile. This PR fixes that by adding a dedicated settings page. A dedicated playlist page was also planned but that will have to be implemented later.
Also, buttons have more personality as they are more rounded.
Fixes #155
New settings page:
Home page:
Login page:
=> Dedicated settings page and UI cleanup

src/app/player/player.component.html
This change allows iPhones to play video inline, rather than forcing full screen.
=> Added change to make player work on iOS without being full screen.

Dockerfile, docker-compose.yml
Needed for the MongoDB backend to make any sense, and also I think it's fair to say that nightly — at least for now — is the absolute best branch to default to.
=> docker-compose.yml: Use YoutubeDL-Material nightly & Dockerfile: bump alpine from 3.12 to latest

Public API v1.yaml, backend/app.js
Added an endpoint to remove all files base on the same search parameters as `api/getAllFiles`. This allows a user to periodically clean all files using a single api call. This is mostly useful when disabling the files manager.
=> Added deleteAllFiles api endpoint

.github/workflows/docker.yml
This optimizes the repo so we don't always push a new nightly on build-unaffected changes like updating the README.md and the like :)
=> Adding ignore parameters to docker build-and-push

backend/youtube-dl.js
Introduced in #602.
Fixed bug that caused verifyBinaryExistsLinux to crash the server on startup. Not sure what conditions caused it to crash but added an additional check that will prevent it from crashing again
Solves #603.
=> Startup crash hotfix

Dockerfile, ffmpeg-fetch.sh
1. Use `ubuntu:20.04 + nodejs 16` base
2. Use of 22.04 need further identification, see https://github.com/Tzahi12345/YoutubeDL-Material/issues/608
3. Clean up some packages
4. Restructure fetching backend and building frontend
5. Rename docker-build.sh to ffmpeg-fetch.sh to prevent confusion naming
6. Add --raw to make pm2 show logs as it
7. Using `ffmpeg-fetch.sh` for compability with `docker build` method
=> Docker nodejs16 upgrade

.github/workflows/docker-release.yml, .github/workflows/docker.yml
Should fix the Docker workflows failing at the end of their run as noted by @GlassedSilver in https://github.com/Tzahi12345/YoutubeDL-Material/pull/633#issuecomment-1153916307
I'm not 100% sure if `secrets.GITHUB_TOKEN` will have the right permissions to push to GHCR - if it does not, there are two options for fixing this:
* Don't push images to GHCR: simply remove the `ghcr.io` line from the `tags` input on the `docker-meta` tasks
* Fix logging in to GHCR for pushes: Add a new repository secret containing a GitHub access token with `repo` read/write permissions and rename `secrets.GITHUB_TOKEN` in the `Log in to GitHub Container Registry` tasks to that secret instead.
=> Fix 403s when pushing to GHCR

backend/utils.js
Skip calculating expected file size if video info does not contain any formats.
Fixes #674
=> Fixed parsing expected file size for videos with no known formats

backend/app.js
`write_ytdl_config` should not be used because the software should always rely on set environment variables.
In this way all the existing env variables will be loaded every time if they exists.
Should also be removed from the wiki: https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Environment-Variables#ytdl_write_config
=> fix: remove write_ytdl_config 

Dockerfile, docker-compose.yml
Moved `ALLOW_CONFIG_MUTATIONS` env variable from docker-compose directly in the Dockerfile, so it is enabled by default.
=> fix: node-config fix environment variable

docker-compose.yml
exposed ports between services in the same stack is not needed
=> fix: remove exposed ports for mongo

Dockerfile, backend/entrypoint.sh
There were two issues relating to permissions and `chown` usage which resulted in long startup times for the docker container. 
1) `/app` was owned by `root` not the default user, and  `find . \! -user "$UID"` includes the targeted directory in its results. This combined with `chown -R` resulted in the entire contents of `/app` getting resigned ownership despite not needed it when using the default user/group. See #717 
1) When using a custom user/group (ie `-e UID=1001 -e UID=1001`), the use of the `-R` flag with `chown` in the entrypoint script resulted in every file under `/app` getting reassigned ownership multiple times, as `find` results would include every file and every directory.
Fixes for these issues:
1) Set `/app` ownership to default user/group in the dockerfile. This …
=> Fixed long docker startup time by optimizing chown use

docker-utils/ffmpeg-fetch.sh
Closes #903
ffmpeg 6.0 is giving issues when downloading twitch streams, it works without issue with 5.1.1
=> Force ffmpeg 5.1.1

backend/subscriptions.js
* Fixed issue where metadata was attempting to be written to a dir that didn't exist yet
* Fixed issue where sub was assumed as duplicate always if using local db
=> Subscription metadata fix

backend/app.js
This adds text/html content type which allows the `X-Content-Type-Options nosniff` header to be used without error on reverse proxies.
Fixes #96,, fixes #125, fixes #772, fixes #983 and maybe others
=> Fix Missing Content-Type

chart/Chart.yaml, chart/templates/ingress.yaml
Fixes #991 
If you're interested I can also add a workflow to do a `helm lint` during PR builds to ensure that the helm chart is usable. I could also modify the release workflow to package the helm chart as a .tgz file to make it easier to use with helm.
Let me know.
=> Ingress template update

backend/app.js, backend/appdata/default.json, backend/config.js, backend/consts.js, backend/notifications.js, backend/test/tests.js, src/app/settings/settings.component.html
Supersedes #998. Uses webhooks instead of polling which simplifies the code updates
Documentation will follow.
=> Add ability to request downloads using telegram (new)
